///Valid Option Codes for ORO
///https://datatracker.ietf.org/doc/html/rfc8415#section-24
#[allow(non_camel_case_types)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OROCode {
    ///Optional
    VENDOR_OPTS,
    SIP_SERVER_D,
    SIP_SERVER_A,
    DNS_SERVERS,
    DOMAIN_LIST,
    NIS_SERVERS,
    NISP_SERVERS,
    NIS_DOMAIN_NAME,
    NISP_DOMAIN_NAME,
    SNTP_SERVERS,
    ///Required for Information-request
    INFORMATION_REFRESH_TIME,
    BCMCS_SERVER_D,
    BCMCS_SERVER_A,
    GEOCONF_CIVIC,
    CLIENT_FQDN,
    PANA_AGENT,
    NEW_POSIX_TIMEZONE,
    NEW_TZDB_TIMEZONE,
    MIP6_HNIDF,
    MIP6_VDINF,
    V6_LOST,
    CAPWAP_AC_V6,
    IPv6_Address_MoS,
    IPv6_FQDN_MoS,
    NTP_SERVER,
    V6_ACCESS_DOMAIN,
    SIP_UA_CS_LIST,
    OPT_BOOTFILE_URL,
    OPT_BOOTFILE_PARAM,
    NII,
    GEOLOCATION,
    AFTR_NAME,
    ERP_LOCAL_DOMAIN_NAME,
    PD_EXCLUDE,
    MIP6_IDINF,
    MIP6_UDINF,
    MIP6_HNP,
    MIP6_HAA,
    MIP6_HAF,
    RDNSS_SELECTION,
    KRB_PRINCIPAL_NAME,
    KRB_REALM_NAME,
    KRB_DEFAULT_REALM_NAME,
    KRB_KDC,
    ///Required for Solicit
    SOL_MAX_RT,
    ///Required for Information-request
    INF_MAX_RT,
    ADDRSEL,
    ADDRSEL_TABLE,
    V6_PCP_SERVER,
    DHCP4_O_DHCP6_SERVER,
    S46_CONT_MAPE,
    S46_CONT_MAPT,
    S46_CONT_LW,
    _4RD,
    _4RD_MAP_RULE,
    _4RD_NON_MAP_RULE,
    DHCP_Captive_Portal,
    MPL_PARAMETERS,
    S46_PRIORITY,
    V6_PREFIX64,
    IPv6_Address_ANDSF,
    ///Avalible for future codes.
    Unknown(u16),
}

impl From<OROCode> for u16 {
    fn from(opt: OROCode) -> Self {
        use OROCode::*;
        match opt {
            VENDOR_OPTS => 17,
            SIP_SERVER_D => 21,
            SIP_SERVER_A => 22,
            DNS_SERVERS => 23,
            DOMAIN_LIST => 24,
            NIS_SERVERS => 27,
            NISP_SERVERS => 28,
            NIS_DOMAIN_NAME => 29,
            NISP_DOMAIN_NAME => 30,
            SNTP_SERVERS => 31,
            INFORMATION_REFRESH_TIME => 32,
            BCMCS_SERVER_D => 33,
            BCMCS_SERVER_A => 34,
            GEOCONF_CIVIC => 36,
            CLIENT_FQDN => 39,
            PANA_AGENT => 40,
            NEW_POSIX_TIMEZONE => 41,
            NEW_TZDB_TIMEZONE => 42,
            MIP6_HNIDF => 49,
            MIP6_VDINF => 50,
            V6_LOST => 51,
            CAPWAP_AC_V6 => 52,
            IPv6_Address_MoS => 54,
            IPv6_FQDN_MoS => 55,
            NTP_SERVER => 56,
            V6_ACCESS_DOMAIN => 57,
            SIP_UA_CS_LIST => 58,
            OPT_BOOTFILE_URL => 59,
            OPT_BOOTFILE_PARAM => 60,
            NII => 62,
            GEOLOCATION => 63,
            AFTR_NAME => 64,
            ERP_LOCAL_DOMAIN_NAME => 65,
            PD_EXCLUDE => 67,
            MIP6_IDINF => 69,
            MIP6_UDINF => 70,
            MIP6_HNP => 71,
            MIP6_HAA => 72,
            MIP6_HAF => 73,
            RDNSS_SELECTION => 74,
            KRB_PRINCIPAL_NAME => 75,
            KRB_REALM_NAME => 76,
            KRB_DEFAULT_REALM_NAME => 77,
            KRB_KDC => 78,
            SOL_MAX_RT => 82,
            INF_MAX_RT => 83,
            ADDRSEL => 84,
            ADDRSEL_TABLE => 85,
            V6_PCP_SERVER => 86,
            DHCP4_O_DHCP6_SERVER => 88,
            S46_CONT_MAPE => 94,
            S46_CONT_MAPT => 95,
            S46_CONT_LW => 96,
            _4RD => 97,
            _4RD_MAP_RULE => 98,
            _4RD_NON_MAP_RULE => 99,
            DHCP_Captive_Portal => 103,
            MPL_PARAMETERS => 104,
            S46_PRIORITY => 111,
            V6_PREFIX64 => 113,
            IPv6_Address_ANDSF => 143,
            Unknown(n) => n,
        }
    }
}

impl From<u16> for OROCode {
    fn from(opt: u16) -> Self {
        use OROCode::*;
        match opt {
            17 => VENDOR_OPTS,
            21 => SIP_SERVER_D,
            22 => SIP_SERVER_A,
            23 => DNS_SERVERS,
            24 => DOMAIN_LIST,
            27 => NIS_SERVERS,
            28 => NISP_SERVERS,
            29 => NIS_DOMAIN_NAME,
            30 => NISP_DOMAIN_NAME,
            31 => SNTP_SERVERS,
            32 => INFORMATION_REFRESH_TIME,
            33 => BCMCS_SERVER_D,
            34 => BCMCS_SERVER_A,
            36 => GEOCONF_CIVIC,
            39 => CLIENT_FQDN,
            40 => PANA_AGENT,
            41 => NEW_POSIX_TIMEZONE,
            42 => NEW_TZDB_TIMEZONE,
            49 => MIP6_HNIDF,
            50 => MIP6_VDINF,
            51 => V6_LOST,
            52 => CAPWAP_AC_V6,
            54 => IPv6_Address_MoS,
            55 => IPv6_FQDN_MoS,
            56 => NTP_SERVER,
            57 => V6_ACCESS_DOMAIN,
            58 => SIP_UA_CS_LIST,
            59 => OPT_BOOTFILE_URL,
            60 => OPT_BOOTFILE_PARAM,
            62 => NII,
            63 => GEOLOCATION,
            64 => AFTR_NAME,
            65 => ERP_LOCAL_DOMAIN_NAME,
            67 => PD_EXCLUDE,
            69 => MIP6_IDINF,
            70 => MIP6_UDINF,
            71 => MIP6_HNP,
            72 => MIP6_HAA,
            73 => MIP6_HAF,
            74 => RDNSS_SELECTION,
            75 => KRB_PRINCIPAL_NAME,
            76 => KRB_REALM_NAME,
            77 => KRB_DEFAULT_REALM_NAME,
            78 => KRB_KDC,
            82 => SOL_MAX_RT,
            83 => INF_MAX_RT,
            84 => ADDRSEL,
            85 => ADDRSEL_TABLE,
            86 => V6_PCP_SERVER,
            88 => DHCP4_O_DHCP6_SERVER,
            94 => S46_CONT_MAPE,
            95 => S46_CONT_MAPT,
            96 => S46_CONT_LW,
            97 => _4RD,
            98 => _4RD_MAP_RULE,
            99 => _4RD_NON_MAP_RULE,
            103 => DHCP_Captive_Portal,
            104 => MPL_PARAMETERS,
            111 => S46_PRIORITY,
            113 => V6_PREFIX64,
            143 => IPv6_Address_ANDSF,
            n => Unknown(n),
        }
    }
}
